/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <string.h>
#include "calcul.h"

void * http_null_1_svc(void *argp, struct svc_req *rqstp) // Va lire dans la ressource désirée selon où on en est
{
	static char * result;

	

	return (void *) &result;
}

reponse * http_request1_1_svc(data *argp, struct svc_req *rqstp)
{
	static reponse  result;
	/*
	char *buffer;
	buffer = malloc((strlen(argp->arg1)+strlen(argp->arg2)+1)*sizeof(char));


	strcat(buffer,argp->arg1);
	strcat(buffer,argp->arg2);


	result.concat=buffer;*/
	 
	return &result;
}
