/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"
#include <stdio.h>
#include <string.h>
CLIENT *clnt;

char* concatener(char* a, char* b) {
		reponse  *resultat;
		data  parametre;
		a[strlen(a)-1]='\0';
		b[strlen(b)-1]='\0';
		parametre.arg1 = a;
		parametre.arg2 = b;
		resultat= calcul_my_strcat_1(&parametre, clnt);

		return resultat->concat;
	}

void calcul_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *calcul_null_1_arg;
	reponse  *result_2;
	data  calcul_my_strcat_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCUL, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = calcul_null_1((void*)&calcul_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = calcul_my_strcat_1(&calcul_my_strcat_1_arg, clnt);
	if (result_2 == (reponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	char a[250] ;
	char b[250] ;


	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	clnt=clnt_create(host, CALCUL, VERSION_UN, "tcp");

	printf("Chaine 1 : ");
	fgets(a,sizeof(a),stdin);

 

	printf("Chaine 2 : ");
	fgets(b,sizeof(b),stdin);

	printf("Concatenation : %s\n",concatener(a,b));

	exit (0);
}
