/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "http.h"

void *
http_null_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

response *
http_request1_1_svc(data1 *argp, struct svc_req *rqstp)
{
	static response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

response *
http_request2_1_svc(data2 *argp, struct svc_req *rqstp)
{
	static response  result;

	/*
	 * insert server code here
	 */

	return &result;
}
